### ISSUE TITLE
Rework use of Pac4j

### ISSUE THREAD

**Issue by dkfellows** [SpiNNakerManchester/RemoteSpiNNaker#163]
Subsequent to the code being written, the way that the Pac4j library has been integrated with Spring Security has _totally_ changed. Multiple major version changes, to the point where there are concepts used in our code that have now gone. We need to reconsider what we're doing, and probably from the ground up.

FWIW, my experience with using Spring Security's own OIDC support in SpiNNakerManchester/JavaSpiNNaker#325 has been good (once I managed to find out what classes were actually participating). I guess that RemoteSpiNNaker is just a “resource controller” in OpenID terms, not a “client”.

So… what should we do?

**Comment by rowleya** [comment]
It is worth noting that the OIDC parts of this code are not in active operation that I know of.  This was done as I thought it was a good idea to authenticate users accessing outputs.  However OIDC bearer tokens are not currently passed on to the code here from the NMPI client that I know of.  So at present, all OIDC code could be stripped out of here for now, and then only added in when needed later.

**Comment by rowleya** [comment]
Similarly, the code that can send outputs to HPC is not currently used.

**Comment by dkfellows** [comment]
> all OIDC code could be stripped out of here

> the code that can send outputs to HPC is not currently used

I'm liking what I'm hearing…
