### ISSUE TITLE
Use random rotating keys for communication between the JobProcessManager and the JobManager

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/RemoteSpiNNaker#2]
The JobProcessManager currently just uses the job id to indicate the current status of a job.  This is clearly insecure.  Instead the JobProcessManager should be assigned a random key at the start, and then every update should produce a new key, which it can use for the next communication.

**Comment by dkfellows** [comment]
Can we assume that the connection layer itself is secure? That's reasonably possible if communication is always with `localhost` or if you're talking to HTTPS (provided non-evil proxies are used). With a secure comms layer, you can just use a secret token that doesn't change, or that only changes when the `JobProcessManager` is booted, probably being given it on stdin if the right option is given. Without a secure comms layer, other measures are very dodgy anyway.

The one complexity is that if you're using tokens that aren't the job id and want to survive a master process restart, you need to store the token. Handling restart will require persistent storage anyway.

**Comment by rowleya** [comment]
Looking back at this (I haven't looked at it properly in a while), I suspect it is a bit of overkill to be honest.  As you suggest, using HTTPS is enough, particularly if certificates are used.  The chances of someone hacking in to this are quite remote in any case...

**Comment by rowleya** [comment]
Wont fix
