### ISSUE TITLE
Update to Spring 6

### ISSUE THREAD

**Issue by dkfellows** [SpiNNakerManchester/RemoteSpiNNaker#258]
I declined #256 precisely because it requires updating the baseline Java version to 17, and our use of the Jakarta EE libraries to 9. But we should consider doing it:

- [ ] Updating the Java version isn't too difficult, but requires rebuilding how we do our CI.
- [ ] Updating the Java version isn't too difficult, but requires alterations to deployment.
- [ ] Updating the JEE version is (potentially) code-intrusive.

----

Links:
* https://github.com/spring-projects/spring-framework/wiki/What%27s-New-in-Spring-Framework-6.x
* https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-6.x

**Comment by dkfellows** [comment]
SpiNNakerManchester/JavaSpiNNaker#647 had the exact same problem.

**Comment by rowleya** [comment]
No longer needed as done in JavaSpiNNaker
