### ISSUE TITLE
JobManager job id should be independent of the NMPI id, to allow other sources of jobs

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/RemoteSpiNNaker#3]
The NMPI job id is currently the only job id in the system.  To avoid clashes with other systems, the JobManager should maintain a map of keys (probably persistent), so that it can run jobs from other sources (including its own future UI).

**Comment by dkfellows** [comment]
The only safe way to do this is to have some sort of SpiNNaker Job Identification Token that we use as the identifier. IDs that come in from external-facing APIs (including to the NMPI) will then need to be mapped to SJITs, which it's pretty easy to do with a DB.

The string form of a SJIT must _not_ look like a number or we'll go crazy.

**Comment by rowleya** [comment]
At present there are actually two ids already - the "spalloc" job id which identifies an allocated machine and the NMPI job id.  The idea of this enhancement was to potentially allow additional sources of jobs other than NMPI jobs; I am unsure how much this might be required from a user standpoint (there isn't a major push for this so far, but I could see it being a potentially useful thing in the future).

I am happy to prefix the actual ids if this makes things easier to follow!  The NMPIManager can handle the mapping in to and out of the SpiNNaker job ids - this keeps this process isolated to the borders (so other managers of external jobs can do the same thing).

**Comment by rowleya** [comment]
Not actually required
