### ISSUE TITLE
Live upload of logs might cause issues

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/RemoteSpiNNaker#62]
The live uploading of logs may cause issues when there is a lot of logging data.  It may therefore be necessary to turn this off for now.

**Comment by dkfellows** [comment]
How live do we actually want the logs? Where is the bottleneck anyway? Can the log upload be moved to a throttled background task?

**Comment by rowleya** [comment]
See #64 where I believe that this is fixed by doing exactly this (throttle the updates).

**Comment by rowleya** [comment]
New API seems to cope
